#!/bin/sh
# Clean old temp files
rm -f *.var
rm -f ./result
echo This test should generate this line only on pass. 
# Generate new output 
for aaa in pcalc.* ; do ../pcalc @$aaa >> ./result;  done
# Compare output with stock output
diff original result

